services:
  frontend:
    container_name: acm-frontend
    image: ghcr.io/mlongo4290/acme-certificates-manager-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: acm-backend
    image: ghcr.io/mlongo4290/acme-certificates-manager-backend:latest
    expose:
      - "3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/acme-certificates-manager
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    volumes:
      - backend_scripts:/app/scripts
      - backend_logs:/app/logs

  mongodb:
    container_name: acm-mongodb
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  backend_scripts:
  backend_logs:
